/** Alle Werte in logischen Arena-Einheiten bzw. Sekunden. */
window.Resonance = window.Resonance || {};
Resonance.Config = {
  arena: { width: 390, height: 620, padding: 24 },
  gameplay: {
    minOrbs: 5,
    maxOrbs: 20,
    impulses: 3,
    requiredRatio: 1,
    chargeTime: 0.5,
    orbRadius: 13,
    moveRadius: 64,
    minDrag: 9,
    hitRadius: 25,
    coreEnergy: 1,
  },
  generator: { minDistance: 50, attempts: 240, includeEveryType: true },
  physics: {
    step: 1 / 120,
    maxFrame: 0.05,
    damping: 1.9,
    restitution: 0.64,
    stopSpeed: 2.8,
    settleTime: 0.28,
    maxSpeed: 280,
    collisionThreshold: 22,
    collisionCooldown: 0.13,
  },
  effects: {
    particles: 12,
    maxParticles: 220,
    maxEffects: 100,
    glow: 0.7,
    trailTime: 0.55,
    completeDuration: 2.5,
    reducedMotion: false,
  },
  audio: {
    master: 1,
    musicMax: 0.5,
    effects: 0.9,
    core: 0.75,
    collision: 0.32,
    fallback: true,
    maxVoices: 28,
  },
  abilities: {
    red: { radius: 100, force: 150 },
    blue: { radius: 100, force: 125 },
    violet: { radius: 100, force: 100, burstForce: 145, pullTime: 0.34 },
    green: { radius: 175, force: 70, recoil: 34, speed: 420 },
    gold: { searchTime: 0.34, travelTime: 0.5 },
    orange: { radius: 70, multiplier: 1.65, rangeMultiplier: 1.15 },
  },
};
